"""
Export router: generates downloadable Jupyter Notebooks (.ipynb)
and PDF executive report exports from the conversation history.
"""
import json
import io
import tempfile
import os
from fastapi import APIRouter, HTTPException
from fastapi.responses import StreamingResponse
import nbformat
from nbformat.v4 import new_notebook, new_markdown_cell, new_code_cell

from models.schemas import ExportRequest

router = APIRouter()


@router.post("/export/notebook")
async def export_notebook(request: ExportRequest):
    """
    Generate a Jupyter Notebook (.ipynb) from the conversation history.
    Each Q&A turn becomes a markdown + code + output cell sequence.
    """
    nb = new_notebook()
    cells = []

    # Title cell
    cells.append(new_markdown_cell(
        "# AI Data Analyst — Exported Analysis\n\n"
        "This notebook was automatically generated by the AI Data Analyst agent.\n\n"
        "---"
    ))

    # Setup cell
    cells.append(new_code_cell(
        "import duckdb\nimport pandas as pd\nimport plotly.express as px\n\n"
        "# Connect to DuckDB (update path if using a persisted database)\n"
        "conn = duckdb.connect(database=':memory:')\n"
        "# TODO: Load your CSV files here\n"
        "# e.g. conn.execute(\"CREATE TABLE sales AS SELECT * FROM read_csv_auto('sales.csv')\")"
    ))

    for i, turn in enumerate(request.history):
        role = turn.get("role", "user")
        content = turn.get("content", "")

        if role == "user":
            cells.append(new_markdown_cell(f"## Question {i // 2 + 1}\n\n**{content}**"))
        elif role == "assistant":
            # Narrative answer
            if turn.get("answer"):
                cells.append(new_markdown_cell(f"### Answer\n\n{turn['answer']}"))

            # Code cell
            if turn.get("code"):
                lang = turn.get("code_language", "sql")
                if lang == "sql":
                    code = f'result_df = conn.execute("""\n{turn["code"]}\n""").df()\nresult_df.head(20)'
                else:
                    code = turn["code"]
                cells.append(new_code_cell(code))

            # Insights
            if turn.get("insights"):
                bullets = "\n".join(f"- {ins}" for ins in turn["insights"])
                cells.append(new_markdown_cell(f"### Key Insights\n\n{bullets}"))

            cells.append(new_markdown_cell("---"))

    nb.cells = cells

    # Serialize to bytes
    buf = io.BytesIO()
    buf.write(nbformat.writes(nb).encode("utf-8"))
    buf.seek(0)

    return StreamingResponse(
        buf,
        media_type="application/octet-stream",
        headers={
            "Content-Disposition": 'attachment; filename="ai_data_analysis.ipynb"'
        },
    )


@router.post("/export/pdf")
async def export_pdf(request: ExportRequest):
    """
    Generate a PDF executive report from the conversation history using fpdf2.
    """
    from fpdf import FPDF

    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()

    # Header
    pdf.set_font("helvetica", "B", 18)
    pdf.set_text_color(108, 99, 255)
    pdf.cell(0, 10, "AI Data Analyst - Executive Report", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("helvetica", "I", 9)
    pdf.set_text_color(128, 128, 128)
    pdf.cell(0, 5, "Generated automatically by yourlocalANALYST", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(5)
    pdf.set_draw_color(200, 200, 220)
    pdf.line(pdf.l_margin, pdf.get_y(), pdf.w - pdf.r_margin, pdf.get_y())
    pdf.ln(8)

    q_idx = 1
    for turn in request.history:
        role = turn.get("role", "user")
        content = turn.get("content", "")

        if role == "user":
            pdf.set_font("helvetica", "B", 12)
            pdf.set_text_color(40, 40, 60)
            pdf.cell(0, 8, f"Q{q_idx}: {content}", new_x="LMARGIN", new_y="NEXT")
            pdf.ln(2)
            q_idx += 1
        elif role == "assistant":
            # Answer / narrative
            answer = turn.get("answer") or content
            if answer:
                pdf.set_fill_color(245, 245, 255)
                pdf.set_text_color(30, 30, 40)
                pdf.set_font("helvetica", "", 10)
                pdf.multi_cell(0, 6, answer, fill=True, new_x="LMARGIN", new_y="NEXT")
                pdf.ln(4)

            # Code
            code = turn.get("code")
            if code:
                lang = (turn.get("code_language") or "SQL").upper()
                pdf.set_font("courier", "B", 9)
                pdf.set_text_color(80, 80, 100)
                pdf.cell(0, 5, f"Executed {lang}:", new_x="LMARGIN", new_y="NEXT")
                pdf.set_fill_color(20, 20, 35)
                pdf.set_text_color(200, 220, 255)
                pdf.set_font("courier", "", 8)
                pdf.multi_cell(0, 4.5, code, fill=True, new_x="LMARGIN", new_y="NEXT")
                pdf.ln(4)

            # Insights
            insights = turn.get("insights")
            if insights:
                pdf.set_font("helvetica", "B", 10)
                pdf.set_text_color(46, 133, 64)
                pdf.cell(0, 6, "Key Insights:", new_x="LMARGIN", new_y="NEXT")
                pdf.set_font("helvetica", "", 9)
                pdf.set_text_color(50, 50, 60)
                for ins in insights:
                    pdf.multi_cell(0, 5, f"- {ins}", new_x="LMARGIN", new_y="NEXT")
                pdf.ln(4)

            pdf.set_draw_color(230, 230, 240)
            pdf.line(pdf.l_margin, pdf.get_y(), pdf.w - pdf.r_margin, pdf.get_y())
            pdf.ln(6)

    buf = io.BytesIO(bytes(pdf.output()))
    buf.seek(0)

    return StreamingResponse(
        buf,
        media_type="application/pdf",
        headers={
            "Content-Disposition": 'attachment; filename="ai_data_analysis_report.pdf"'
        },
    )
